### ISSUE TITLE
How do I get this onto my iPhone?

### ISSUE THREAD

**Issue by gpotok** [SelfControlApp/selfcontrol-ios#1]
How do I get this onto my iPhone? I tried changing code signing, as I did a while ago when I successfully built the original SelfControl (the OS X desktop app, though when Itried to do so again, recently, I was not able to*), so I believe it is something else.

Is this a situation where I either pay Apple $99 or jailbreak? Because I don't want to do either of those. What can I do?

I don't remember the error messages, but if you think you can help me, I'll get back to you. Thanks!

*Though i didn't pursue that because it is available as an application/executable/zip file on the self-control website homepage

**Comment by cstigler** [comment]
You definitely don't want this on your phone in its current state. It is not a finished application. It'll mostly just break, if you can figure out how to use it at all. Up until last night it didn't even block websites.

I'd advise that you wait until it's released in a few months, and then you can just download it from the App Store!
